---
title: "API (Cont.) and Tidy Data"
author: "Fadel Megahed"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_download: TRUE
    code_folding: show
    number_sections: TRUE
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CryptoCompare API

```{r}
cc_request = "https://min-api.cryptocompare.com/data/v2/histoday?fsym=SHIB&tsym=USD&limit=100&api_key=a0850692beafc12f12226f0322853380f88a9c5560248afc2d07b55a53f0e63e"

# visually from the browswer, we saw the nesting with the brackets
# indicating that we are getting a JSON response

cc_response = jsonlite::fromJSON(txt = cc_request)

# from the environment the response was a list of 6 
names(cc_response)

# inside the response, there was a data list that had four sublists
# the fourth one being also called Data and that contains our data frame
shib_list = cc_response[['Data']] # cc_response$Data
shib_df = shib_list[['Data']]

# try to make the time more understandable
# seems to be a unix time (number of seconds since Jan 1, 1970)
shib_df$time = lubridate::as_datetime(shib_df$time) |> 
  lubridate::as_date() # this will remove the time piece (visually corresponds to removing the UTC)
```


# Pivotting

## Pivot Longer

```{r pivot_longer}
# an example of a wide table since the year variable is in multiple cols
tidyr::table4a

table4a_tidy = tidyr::pivot_longer(
  data = tidyr::table4a, 
  cols = `1999`:`2000`,
  names_to = 'year',
  values_to = 'cases'
)

table4b_tidy = tidyr::pivot_longer(
  data = tidyr::table4b, 
  cols = `1999`:`2000`,
  names_to = 'year',
  values_to = 'population'
)

table4_complete = dplyr::left_join(
  x = table4a_tidy, y = table4b_tidy, by = c('country', 'year') 
)

```


## Pivot Wider

```{r pivot_wider}
tidyr::table2

table2_tidy = tidyr::pivot_wider(
  data = tidyr::table2,
  names_from = 'type',
  values_from = 'count'
)

```


# Seperate 

```{r sep}
tidyr::table3

table3_tidy_a = tidyr::separate(
  data = tidyr::table3, col = 'rate', into = c('cases', 'population')
)

# we can explicitly set the separator based on our data
table3_tidy_b = tidyr::separate(
  data = tidyr::table3, col = 'rate', into = c('cases', 'population'),
  sep = '/'
)
```


# USA Facts

```{r covid}
covid_df = readr::read_csv('covid_deaths_usafacts.csv')

covid_df_tidy = covid_df |> 
  tidyr::pivot_longer(
    cols = 5:1269,
    names_to = 'date',
    values_to = 'deaths'
  )
```






