---
title: "Web Scraping in R and Python"
author: "Fadel Megahed"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: simplex
    code_folding: show
    code_download: TRUE
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Web Scraping in R

We **can** use the `results = 'hold'` to show all the outputs at the end of the code chunk.

```{r isa_courses_r, results='hold'}

# step 0 - know the url for what you want to scrape
isa_url = "https://bulletin.miamioh.edu/courses-instruction/isa/"

# step1 - read the html in R
html_content = rvest::read_html(x = isa_url)
names(html_content) # to printout the names of the 2 sublists

# step 2 - we will select specific parts of the document for parsing/reading
# x is the read_html from the previous step
# css = 'strong' per what we got from the selector gadget
course_titles = rvest::html_elements(
  x = html_content, css = 'strong'
)

# Step 3 - cleaning/removing the HTML tags so it looks like how we read it
# on the page
cleaned_course_titles = rvest::html_text2(course_titles)

# Start from Step 2 and save the course descriptions in course_desc and cleaned_course_desc and we will talk about that once you are done
course_desc = rvest::html_elements(x = html_content, '.courseblockdesc')

# step 3 - cleaning
cleaned_course_desc = rvest::html_text2(course_desc)

# Step 4 - Put the course titles and descriptions in a data.frame or a tibble
isa_df = tibble::tibble(
  course_title = cleaned_course_titles,
  course_description = cleaned_course_desc
)
head(isa_df)

readr::write_csv(x = isa_df, '05_isa_courses_r.csv')
```

# Web Scraping in Python

```{python isa_courses_python, results='hold'}
import requests as req
import bs4
import pandas as pd

# Step 0
isa_url = "https://bulletin.miamioh.edu/courses-instruction/isa/"

# Step 1 - read the HTML contents in Python
html_content = req.get(isa_url)
parsed_content = bs4.BeautifulSoup(html_content.content)

# Step 2
# based on the selector gadget
# almost the equivalent of rvest::html_elements
course_names = parsed_content.select('strong')

# Step 3 - clean this
course_names[0]
course_names[0].text # shows that what we want is in text

# via list comprehension in Python
cleaned_course_names = [course_name.text for course_name in course_names]
cleaned_course_names = [course_name.replace('\xa0', ' ') for course_name in cleaned_course_names] # overwriting the list by replacing the '\xa0' by ' '

course_desc = parsed_content.select('.courseblockdesc')
course_desc[0].text
cleaned_course_descs = [i.text for i in course_desc]
cleaned_course_descs = [i.replace('\xa0', ' ') for i in cleaned_course_descs] # overwriting the list by replacing the '\xa0' by ' '
cleaned_course_descs = [i.replace('\n', ' ') for i in cleaned_course_descs] # overwriting the list by replacing the '\n' by ' '

isa_df = pd.DataFrame(
  {'course_title': cleaned_course_names, 'course_description': cleaned_course_descs}
)

isa_df.to_csv('05_isa_courses_py.csv')
```




