---
title: "Connecting to APIs"
author: "Fadel Megahed"
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: TRUE
    code_folding: show
    code_download: TRUE
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Wikipedia

```{r wiki_ex}
rvest::read_html("https://en.wikipedia.org/wiki/Miami_RedHawks_football") |> 
  rvest::html_element("table.wikitable") |> 
  rvest::html_table() -> element_result

class(element_result) # in plain English; data frame/tibble

tail(element_result)

rvest::read_html("https://en.wikipedia.org/wiki/Miami_RedHawks_football") |> 
  rvest::html_elements("table.wikitable") |> # note the change to elements 
  rvest::html_table() -> elements_output

retired_numbers = elements_output[[8]] # I know by inspecting the list that this is table 8

# a general enough selector
rvest::read_html("https://en.wikipedia.org/wiki/Miami_RedHawks_football") |> 
  rvest::html_elements("#mw-content-text > div.mw-parser-output > table") |> # note the change to elements 
  rvest::html_table() -> table_examples

# this now produces 11 tables instead of 9
# because there are two tables that do not have the class wikitable
```


# Accu Weather

```{r}
# how the URL is constructed
base_url = "http://dataservice.accuweather.com/forecasts/v1/daily/5day/"
location_key = 340019
post_key_part = "?apikey="
api_key = 'mDyIYQMWJGLgEiAmGkEIlkoS3I4JYAwo' # this part is different for each of us

# note paste0 instead of paste since we do not want space between the four parts
# R is different than Python since it forces the location key to be a string
# python would have given you an error since it cannot combine strings with floats
request_url = paste0(base_url, location_key, post_key_part, api_key)

# from Chrome, we noticed that the output is a JSON response
accu_response = jsonlite::fromJSON(txt = request_url)

# names here to make sense of the two sublists in the response
names(accu_response)
oxford_forecasts = accu_response$DailyForecasts # from the second sublist; I learned that here is where my forecasts are stored

oxford_forecasts$EpochDate = 
  # converts unix time (seconds since Jan 1, 197) to datetime
  lubridate::as_datetime(oxford_forecasts$EpochDate) |>
  # removes the time part and keeps us with only dates
  lubridate::as_date()
```

# Census Example

## API

```{r census_api}
c_key = 'befa92e72cdca31bac55b43f87e207201c10f0ef'
ohio_population = 
  jsonlite::fromJSON("https://api.census.gov/data/2020/dec/dhc?get=P1_001N&for=state:39")

# col names for ohio population is in the first row
colnames(ohio_population) = ohio_population[1,]

# this is not the cleanest but it works 
# removed the first row but when I did that it converted into a chr vector
# transposed it t() so that when I convert it back into a data frame 
# I have two columns and 1 row
ohio_population = ohio_population[-1,] |> t() |> data.frame()

  
```

