---
title: "Visualizing Stock Data: A Simple Example"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(magrittr)
library(tidyquant)
library(shiny)
library(fontawesome)
library(plotly)
library(DT)


stocks = c('FB', 'AAPL', 'GOOG', 'NFLX', 'MCD', 'F', 'TSLA')
```

# Sidebar {.sidebar}

**Global Choices**
  
```{r globalChoices}
selectInput(inputId = 'periodicity', # name of the sublist in my input
            label = 'Select Unit of Aggregation', # Printout in R
            choices = c('daily', 'weekly', 'monthly'), # possible categorical values
            selected = 'monthly') # default pick

selectInput(inputId = 'tickers',
            label = 'Pick stocks of interest',
            choices = stocks,
            selected = c('AAPL', 'FB', 'GOOG', 'NFLX'),
            multiple = TRUE)
```

<br><br>

---
  
<br><br>
  
**Created By:** Fadel Megahed

**Updated on:** `r format(Sys.Date(), '%b %d, %Y')`

<br><br>
  
---

<br><br>
  
**Contact Information:**
  
`r fa("twitter", fill = 'steelblue')` $~$ [\@FadelMegahed](https://twitter.com/fadelmegahed)

`r fa("linkedin", fill = 'steelblue')` $~$ [Fadel Megahed](https://www.linkedin.com/in/fadel-megahed-289046b4)

<br><br>
  
# Getting the Data
  
```{r rawData}
stocks_df = reactive(
  tq_get(x = input$tickers, from = "2010-01-01", 
         periodicity = input$periodicity)
)

renderDataTable(
  datatable(
    data = stocks_df() %>% select(symbol, date, open, close, volume)
  )
)

```

# Plot (Static)

```{r plot}
renderPlot({
  stocks_df() %>% 
    ggplot(aes(x = date, y = adjusted, group = symbol, color = symbol)) +
    geom_line() +
    facet_wrap(~symbol, ncol = 2, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "top") 
})

```

# Plot (Interactive)

```{r plot2}
renderPlotly({
   stocks_df() %>% 
    ggplot(aes(x = date, y = adjusted, group = symbol, color = symbol)) +
    geom_line() +
    facet_wrap(~symbol, ncol = 2, scales = "free_y") +
    theme_bw() +
    theme(legend.position = "top") 
  ggplotly()
})
```