---
title: "Web Scraping in R and Python"
author: "Fadel Megahed"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_download: TRUE
    code_folding: show
    number_sections: TRUE
    theme: simplex
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Web Scraping in R

You **can** use `results = 'hold'` to printout all the results after the end of the code chunk.

```{r web_scrape_r, results='hold'}
# step 0: know the URL of your web page
isa_url = 'https://bulletin.miamioh.edu/courses-instruction/isa/'

# step 1 - read the HTML file in R
html_contents = rvest::read_html(isa_url)

# Steps 2-3 (we can do that multiple times to get what we want from the page)

# Step 2 - Select specific parts of the page
# first input is the read webpage from step 1
# second input will depend on what you want; use selector gadget for guidance
course_titles = rvest::html_elements(
  x = html_contents, css = 'strong'
)
head(course_titles)


# Step 3: Remove the HTML tags to make this more of a human readable output
# given that we are pulling text, we will use a cleaning function specific to text
clean_course_titles = rvest::html_text2(course_titles)
head(clean_course_titles)

# repeating for course descriptions
course_descs = rvest::html_elements(
  x = html_contents, css = '.courseblockdesc'
)

clean_course_descs = rvest::html_text2(course_descs)
head(clean_course_descs)


# Step 4 - Put in a format that you can export
isa_df = tibble::tibble(
  title = clean_course_titles,
  description = clean_course_descs
)

readr::write_csv(x = isa_df, file = 'isa_courses_r.csv')
```


---

# Web Scraping in Python

```{python web_scrape_py}
import requests
import bs4
import pandas as pd

# step 0: know the URL of your web page
isa_url = 'https://bulletin.miamioh.edu/courses-instruction/isa/'

# Step 1: Read the file in Python
html_content = requests.get(isa_url)
# content is stored in html_content.content
html_parsed = bs4.BeautifulSoup(html_content.content)

# Step 2: Select What you are interested in
course_titles = html_parsed.select('strong')
course_titles[0] # will show the HTML tags 
course_titles[0].text # we will leverage this to clean the text in step 3

# Step 3: Remove the HTML tags
# we will use the concept of list comprehension in Python to do that
clean_course_titles = [i.text for i in course_titles]
clean_course_titles = [i.replace('\xa0', ' ') for i in clean_course_titles]
clean_course_titles[0:5]


# Same approach for Course Descriptions
course_descs = html_parsed.select('.courseblockdesc')
clean_course_descs = [i.text for i in course_descs]
clean_course_descs = [i.replace('\xa0', ' ').replace('\n', ' ') for i in clean_course_descs] # optional

isa_df = pd.DataFrame(
  {'course_title': clean_course_titles, 'course_desc': clean_course_descs}
)

isa_df.to_csv('isa_courses_py.csv', index = False)

```

