---
title: "API Cont and Tidy Data"
author: "Fadel Megahed"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_download: TRUE
    code_folding: show
    number_sections: TRUE
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cryptocompare API

```{r cc}
cc_request = "https://min-api.cryptocompare.com/data/v2/histoday?fsym=SHIB&tsym=USD&limit=100&api_key=0327a7419d40e3044ed709ae540da577c8c8c3253ed95cff77e6d952e68e8fbf"

cc_response = jsonlite::fromJSON(txt = cc_request)

cc_data_list = cc_response[['Data']]
cc_data_df = cc_data_list[['Data']]

# alternatively
crypto_df = cc_response[['Data']][['Data']]


# let us convert time to something that we can understand
# This data based on the API call is daily data (so time is really irrelevant); we want the dates

crypto_df$time = lubridate::as_datetime(crypto_df$time)

head(crypto_df$time) # returns a dttm vector which has the date and UTC for time

# we will extract only the date from the datetime object and we will store it in date
crypto_df$date = lubridate::as_date(crypto_df$time)

dplyr::glimpse(crypto_df)
```


# Tidy Data

## Preface

Answering the question about whether adding rate to the original data would make it tidy and the answer is **yes**.

```{r rate_from_original_data}
t1 = tidyr::table1 |> 
  dplyr::mutate(rate = cases/population)

t1
```

## Pivot Operations

### Pivot Longer

```{r pivot_longer}
t4a_tidy = 
  tidyr::table4a |> 
  tidyr::pivot_longer(
    cols = `1999`:`2000`, # you can also use their numbers 2:3
    names_to = 'year', # what the column from 1999:2000 will be called
    values_to = 'cases' # for their values, what we will name them
  )

t4a_tidy

t4b_tidy = 
  tidyr::table4b |> 
  tidyr::pivot_longer(
    cols = `1999`:`2000`, # you can also use their numbers 2:3
    names_to = 'year', # what the column from 1999:2000 will be called
    values_to = 'population' # for their values, what we will name them
  )


# In R: _join from the dplyr package
# In Python: merge from pandas
table4_tidy = dplyr::left_join(
  x = t4a_tidy, y = t4b_tidy, by = c('country', 'year')
)

table4_tidy2 = dplyr::right_join(
  x = t4a_tidy, y = t4b_tidy, by = c('country', 'year')
)

table4_tidy3 = dplyr::full_join(
  x = t4a_tidy, y = t4b_tidy, by = c('country', 'year')
)

table4_tidy
```


### Pivot Wider

```{r wider}
tidyr::table2 |> 
  tidyr::pivot_wider(
    names_from = 'type',
    values_from = 'count'
  ) -> table2_tidy
```



## Seperate

```{r sep}
table3_tidy = tidyr::separate( 
  data = tidyr::table3, col = rate, into = c('cases', 'population')
)

table3_tidy2 = tidyr::separate( 
  data = tidyr::table3, col = rate, into = c('cases', 'population'), sep = '/'
)
```


# COVID 

```{r covid}
covid_df = readr::read_csv('covid_deaths_usafacts.csv')

covid_tidy1 = tidyr::pivot_longer(
  data = covid_df, cols = 5:1269, names_to = 'date', values_to = 'deaths'
)
```





